### ISSUE TITLE
Thumbnailer return JSON error instead of image

### ISSUE THREAD

**Issue by joshuaavalon** [directus/docker#10] opened 2018-12-05 14:08 UTC
# Bug Report

## Steps to Reproduce

1. Create a collection with a file field
2. Upload an image
3. Go back to collection page

## Expected Behavior

Show thumbnail.

## Actual Behavior
Status code 404

```json
{"error":{"error":8,"message":"API Environment Configuration Not Found: thumbnail"}}
```

## Other Context & Screenshots

![directus](https://user-images.githubusercontent.com/7152420/49518604-ffeb4300-f8d9-11e8-995c-4f884f5ffd99.PNG)

The original image is fine. Only thumbnail is having problem.

## Technical Details

[**docker-compose.yml**](https://github.com/directus/docker/blob/e586fe0f124612deccf4176d3ca6e2b012ed94b5/examples/single-api/docker-compose.yml) from example
```yaml
version: "3"

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "somedb"
      MYSQL_ROOT_PASSWORD: "rootpassword"
      MYSQL_USER: "someusername"
      MYSQL_PASSWORD: "somepassword"
    ports:
      - 3306:3306

  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: "somedb"
      DATABASE_USERNAME: "someusername"
      DATABASE_PASSWORD: "somepassword"
      ADMIN_EMAIL: "admin@localhost.com"
      ADMIN_PASSWORD: "directusrocks"
    ports:
      - 7000:80

  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; http://localhost:7000/_/"
    ports:
      - 8000:80
```

**Comment by stickgrinder** [comment] 2018-12-06 08:02
I'm posting this here since it may be related: I think configuration is OK in my case but thumbnails can't be generated. The request for `thumbnail/_/` just returns a 404. The `index.php` file that is supposed to generate the thumbnail if it's not there isn't invoked at all. The culprit here is  the missing nginx configuration for the `thumbnail` location (also see https://github.com/directus/api/issues/577#issuecomment-441248726).

I spent quite a lot of time on this issue and I'm grinding to a halt... almost out of ideas.

The current situation is this. Nginx configuration follows:

```
    ...
    client_max_body_size 100M;

    ### New portion
    location /thumbnail/ {
        rewrite /thumbnail/((?!index\.php).*) /thumbnail/index.php?$1 last;
    }
   ### End of new portion

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        ...
```

The idea to pass the query part to `index.php` is a remnant of a desperate attempt... still it's totally unclear to me how is the app supposed to be aware of the original request. Maybe Apache passes it over when a rewrite happens?
*Clarifications on this would be very welcome!*

Anyway, that's the result for such a configuration:

```
api_1_6f68fecc6df5 | 2018/12/06 07:43:04 [notice] 247#247: *4010 "/thumbnail/((?!index\.php).*)" matches "/thumbnail/_/200/200/crop/good/logo_spark_white.png", client: 192.168.32.1, server: _, request: "GET /thumbnail/_/200/200/crop/good/logo_spark_white.png HTTP/1.1", host: "api.directus.myhost.loc", referrer: "http://app.directus.myhost.loc/"
api_1_6f68fecc6df5 | 2018/12/06 07:43:04 [notice] 247#247: *4010 rewritten data: "/thumbnail/index.php", args: "_/200/200/crop/good/logo_spark_white.png", client: 192.168.32.1, server: _, request: "GET /thumbnail/_/200/200/crop/good/logo_spark_white.png HTTP/1.1", host: "api.directus.myhost.loc", referrer: "http://app.directus.myhost.loc/"
api_1_6f68fecc6df5 | 2018/12/06 07:43:04 [notice] 247#247: *4021 "/thumbnail/((?!index\.php).*)" matches "/thumbnail/_/200/200/crop/good/thumbs_up.png", client: 192.168.32.1, server: _, request: "GET /thumbnail/_/200/200/crop/good/thumbs_up.png HTTP/1.1", host: "api.directus.myhost.loc", referrer: "http://app.directus.myhost.loc/"
api_1_6f68fecc6df5 | 2018/12/06 07:43:04 [notice] 247#247: *4021 rewritten data: "/thumbnail/index.php", args: "_/200/200/crop/good/thumbs_up.png", client: 192.168.32.1, server: _, request: "GET /thumbnail/_/200/200/crop/good/thumbs_up.png HTTP/1.1", host: "api.directus.myhost.loc", referrer: "http://app.directus.myhost.loc/"
api_1_6f68fecc6df5 | 192.168.32.1 - - [06/Dec/2018:07:43:04 +0000] "GET /thumbnail/_/200/200/crop/good/bandb-bg.jpg HTTP/1.1" 404 42 "http://app.directus.myhost.loc/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
api_1_6f68fecc6df5 | 192.168.32.1 - - [06/Dec/2018:07:43:04 +0000] "GET /thumbnail/_/200/200/crop/good/avatar_sf.jpg HTTP/1.1" 404 42 "http://app.directus.myhost.loc/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
api_1_6f68fecc6df5 | 192.168.32.1 - - [06/Dec/2018:07:43:04 +0000] "GET /thumbnail/_/200/200/crop/good/avatar_sf_2018.jpg HTTP/1.1" 404 42 "http://app.directus.myhost.loc/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
api_1_6f68fecc6df5 | 192.168.32.1 - - [06/Dec/2018:07:43:04 +0000] "GET /thumbnail/_/200/200/crop/good/codecode.jpg HTTP/1.1" 404 42 "http://app.directus.myhost.loc/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
api_1_6f68fecc6df5 | 192.168.32.1 - - [06/Dec/2018:07:43:04 +0000] "GET /thumbnail/_/200/200/crop/good/logo_spark_white.png HTTP/1.1" 404 42 "http://app.directus.myhost.loc/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
api_1_6f68fecc6df5 | 192.168.32.1 - - [06/Dec/2018:07:43:04 +0000] "GET /thumbnail/_/200/200/crop/good/thumbs_up.png HTTP/1.1" 404 42 "http://app.directus.myhost.loc/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0" "-"
```

From what I see rewriting is happening (I activated the rerwiting debug in the conf also). Unclear what this means in practical terms since nginx tries to serve the resource anyway - and it fails.

I tried to slam a `http_status_code(500); die;` as first line of `thumbnail/index.php' but the logs remain unaffected by this so my best guess is `index.php` is still out of this merry-go-round...

I tried to map the request/response cycle by ngrep (`ngrep -q -W byline port 8090` if you want to try it by yourself) but didn't get a lot out of it.

Any idea from some nginx ninja out there? Am I missing something?

**Comment by makote** [comment] 2018-12-06 16:09
I'm having a similar problem running an instance on a webfaction acount. Everything seems fine. but the index.php file never gets called. 

200x200 thumbnails do work I imagine this is caused by the upload via the Application.

**Comment by stickgrinder** [comment] 2018-12-06 16:11
@makote it would suffice to check if thumbnails are actually already there... try to move or rename the file and see if it gets re-generated.

**Comment by makote** [comment] 2018-12-07 18:36
Funny thing there is only one image that was generated its 200x200 and its the first Image I called/uploaded. Everything else afterwards hasn't been created. 

However when i call the file via the api, it sends links to the 4 sizes that where specified at the settings level.

also, my /thumbnail/index.php is not being procesed as I added a 500 error too to figure out if it had been triggered.

**Comment by stickgrinder** [comment] 2018-12-10 10:21
The exact same thing is happening here... index.php is ignored.
I wonder how you managed to get one generated. Are you sure you were running Directus in the container?

**Comment by joshuaavalon** [comment] 2018-12-11 02:56
@benhaynes Any updates on this?

**Comment by benhaynes** [comment] 2018-12-11 04:00
Unfortunately I don't have much experience with Docker so I can't help much. This Docker work has mostly been provided by the community.

@WellingGuzman @rijkvanzanten  – any thoughts on this?

**Comment by makote** [comment] 2018-12-11 16:13
@stickgrinder im not running on docker, I came here from your other post. 

**My current workaround:**
I manually added the sizes to thumbnailer.php and now it works.

`  public function getSupportedThumbnailDimensions()
    {
        $defaultDimension = '200x200';
        $dimensions =  $this->parseCSV(
            ArrayUtils::get($this->getConfig(), 'thumbnail_dimensions')
        );
        if (!in_array($defaultDimension, $dimensions)) {
            array_unshift($dimensions, $defaultDimension);
        }
        return $dimensions;
    }
`

**Comment by stickgrinder** [comment] 2018-12-11 17:21
@makote sorry, I didn't get it.

What `$this->getConfig()` returns when called in the commented line? Is the `thumbnail_dimensions` key present?

**Comment by makote** [comment] 2018-12-12 00:31
@stickgrinder yep, the thumbnail dimensions is present in the DB, however I don't believe the call is the problem. I believe since index.php is not triggered. it does it by default somehow?.

Noobie coder here. But this works for generating all of the above sizes and the other approach didn't.

**Comment by RyanPrice-King** [comment] 2018-12-12 09:45
where is thumb_root in the api.php?
 'adapter' => getenvs('STORAGE_ADAPTER', 'local'),
                'root' => getenvs('STORAGE_ROOT', 'public/uploads/_/originals'),
                'root_url' => getenvs('STORAGE_ROOT_URL', '/uploads/_/originals'),
                'key' => getenvs('STORAGE_KEY', 's3-key'),
                'secret' => getenvs('STORAGE_SECRET', 's3-secret'),
                'region' => getenvs('STORAGE_REGION', 's3-region'),
                'version' => getenvs('STORAGE_VERSION', 's3-version'),
                'bucket' => getenvs('STORAGE_BUCKET', 's3-bucket').

could this be why thumbs are not showing as it appears to be missing from the config?
https://github.com/directus/docker/blob/master/projects/api/api.php

**Comment by makote** [comment] 2018-12-12 14:53
@stickgrinder its actually a weird setup since its Webfaction. It runs apache in the shared instance but the public layer is served by nginx. 

However. if someone can help me understand why when I hardcode the values. The thumbnailer api is called, but when values get pulled from settings it doesn't work.

**Comment by aiomaster** [comment] 2018-12-18 20:05
I tried to use the patch from @makote here https://github.com/directus/docker/issues/10#issuecomment-446261204 in my docker container but it does not help.
I also tried to add the `thumb_root` in the api.php like @RyanPrice-King suggested, but nothing helped here.
No thumbnails get generated.
Any ideas?

**Comment by WoLfulus** [comment] 2018-12-19 15:06
I patched with all suggestions present in this post, and it was nginx routing problems indeed.

**Comment by stickgrinder** [comment] 2018-12-19 16:37
Great work @WoLfulus! Many thanks for your effort! I took a look at your commit and I'm puzzled about the nested `location` to bring PHP files handlers in each single statement.

Don't want to bother you for stuff I can learn from documentation but if you don't mind sharing some insight on why this is necessary (or linking a resource) it would be great!

You rock man, thanks! :+1: :heart:

**Comment by WoLfulus** [comment] 2018-12-19 19:18
Hi @stickgrinder 

We're on the same boat. There's probably a better way to write that nginx configuration file, that was just how I ended up doing it. I tried several configs before leaving it that way.

I wasn't aware that thumbnails were generated on demand when the file was requested, so I spent most of the time tracking before finding the `public/thumbnail` folder 😆

**Comment by WoLfulus** [comment] 2018-12-19 19:21
From the tests I've have, it should work after next release. I'm closing this for now, but we can reopen this if the problem persists.

**Closed by WoLfulus** 2018-12-19 19:21 UTC
Labels: bug

**Comment by aiomaster** [comment] 2018-12-19 20:02
When will a new release be pushed? Do we have to wait for the next directus api or app release or can you push the fix right now?
Thanks again for fixing this.

**Comment by rijkvanzanten** [comment] 2018-12-19 21:46
Good news, I didn't get around to releasing 7.0.12 past Friday, so the next release is going to be today!

**Comment by rjwismar** [comment] 2018-12-21 09:40
I have also a problem with that.
I figure out that '$this->getConfig()' will return a array with the needed entry 'thumbnail_demensions' but the 'ArrayUtils' can't get them. The 'ArrayUtils' return NULL but not the configured settings.
```
/**
     * Return supported thumbnail file dimesions
     *
     * @return array
     */
    public function getSupportedThumbnailDimensions()
    {
        $defaultDimension = '200x200';

        // returns NULL
        $dimensions =  $this->parseCSV(
             ArrayUtils::get($this->getConfig(), 'thumbnail_dimensions')
        );
        
        if (!in_array($defaultDimension, $dimensions)) {
            array_unshift($dimensions, $defaultDimension);
        }
        
        return $dimensions;
    }
```

In this example I get the integer key of 'thumbnail_demensions' and in the next step I get the value of this key

```
/**
     * Return supported thumbnail file dimesions
     *
     * @return array
     */
    public function getSupportedThumbnailDimensions()
    {
        $defaultDimension = '200x200';

        $key = array_search('thumbnail_dimensions', array_column($this->getConfig(), 'key'));

        $dimensions =  $this->parseCSV(
            $this->getConfig()[$key]['value']
        );
        
        if (!in_array($defaultDimension, $dimensions)) {
            array_unshift($dimensions, $defaultDimension);
        }
        
        return $dimensions;
    }
```
