### ISSUE TITLE
CORS error when opening the app

### ISSUE THREAD

**Issue by PostPollux** [directus/docker#22] opened 2019-02-07 18:08 UTC
I just used "docker-compose up" with the current "examples/single-api/docker-compose.yml" as my dockerfile.
I didn't change anything on this dockerfile. So I suppose it should work. But I get an CORS error when i go to the app under localhost:8000. The login fields are greyed out and it says, that it couldn't reach the api. I tested it with Brave browser and with Firefox.
Here are the screenshots:

![directus bug](https://user-images.githubusercontent.com/9008901/52432898-ffef0580-2b0b-11e9-8b5a-72a98d782b43.png)

![directus bug_firefox](https://user-images.githubusercontent.com/9008901/52432913-08dfd700-2b0c-11e9-8192-34e9f7cd3cd7.png)

Any help is much appreciated!

<details>
<summary>Here is the log from docker-compose up:</summary>
<pre>
docker-compose up
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Creating network "directus_test_default" with the default driver
Creating directus_test_database_1 ... done
Creating directus_test_app_1      ... done
Creating directus_test_api_1      ... done
Attaching to directus_test_app_1, directus_test_api_1, directus_test_database_1
api_1       | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
api_1       | [s6-init] ensuring user provided files have correct perms...exited 0.
api_1       | [fix-attrs.d] applying ownership & permissions fixes...
api_1       | [fix-attrs.d] done.
api_1       | [cont-init.d] executing container initialization scripts...
api_1       | [cont-init.d] done.
api_1       | [services.d] starting services
api_1       | nginx: waiting for fpm...
api_1       | [services.d] done.
database_1  | Initializing database
database_1  | 2019-02-07T17:52:25.900788Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
api_1       | [07-Feb-2019 17:52:25] NOTICE: fpm is running, pid 190
api_1       | [07-Feb-2019 17:52:25] NOTICE: ready to handle connections
database_1  | 2019-02-07T17:52:26.192535Z 0 [Warning] InnoDB: New log files created, LSN=45790
database_1  | 2019-02-07T17:52:26.270694Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
database_1  | 2019-02-07T17:52:26.342095Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 21325aa8-2b01-11e9-ae30-0242c0a86004.
database_1  | 2019-02-07T17:52:26.346724Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
database_1  | 2019-02-07T17:52:26.349080Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
api_1       | nginx: waiting for database...
database_1  | 2019-02-07T17:52:27.745495Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:27.745521Z 1 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:27.745531Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:27.745545Z 1 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:27.745550Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:27.745560Z 1 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:27.745588Z 1 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:27.745597Z 1 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | Database initialized
database_1  | Initializing certificates
database_1  | Generating a RSA private key
database_1  | .............................................................................................................+++++
database_1  | .......................................................+++++
database_1  | unable to write 'random state'
database_1  | writing new private key to 'ca-key.pem'
database_1  | -----
database_1  | Generating a RSA private key
database_1  | .+++++
database_1  | ..................+++++
database_1  | unable to write 'random state'
database_1  | writing new private key to 'server-key.pem'
database_1  | -----
database_1  | Generating a RSA private key
database_1  | ............................................................................+++++
database_1  | ............................+++++
database_1  | unable to write 'random state'
database_1  | writing new private key to 'client-key.pem'
database_1  | -----
database_1  | Certificates initialized
database_1  | MySQL init process in progress...
database_1  | 2019-02-07T17:52:30.866084Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
database_1  | 2019-02-07T17:52:30.867127Z 0 [Note] mysqld (mysqld 5.7.24) starting as process 90 ...
database_1  | 2019-02-07T17:52:30.870047Z 0 [Note] InnoDB: PUNCH HOLE support available
database_1  | 2019-02-07T17:52:30.870060Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
database_1  | 2019-02-07T17:52:30.870064Z 0 [Note] InnoDB: Uses event mutexes
database_1  | 2019-02-07T17:52:30.870067Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
database_1  | 2019-02-07T17:52:30.870069Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
database_1  | 2019-02-07T17:52:30.870071Z 0 [Note] InnoDB: Using Linux native AIO
database_1  | 2019-02-07T17:52:30.870339Z 0 [Note] InnoDB: Number of pools: 1
database_1  | 2019-02-07T17:52:30.870460Z 0 [Note] InnoDB: Using CPU crc32 instructions
database_1  | 2019-02-07T17:52:30.871797Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
database_1  | 2019-02-07T17:52:30.879306Z 0 [Note] InnoDB: Completed initialization of buffer pool
database_1  | 2019-02-07T17:52:30.881067Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
database_1  | 2019-02-07T17:52:30.892433Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
database_1  | 2019-02-07T17:52:30.903717Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
database_1  | 2019-02-07T17:52:30.903768Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
database_1  | 2019-02-07T17:52:30.930805Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
database_1  | 2019-02-07T17:52:30.932804Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
database_1  | 2019-02-07T17:52:30.932835Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
database_1  | 2019-02-07T17:52:30.934696Z 0 [Note] InnoDB: 5.7.24 started; log sequence number 2591440
database_1  | 2019-02-07T17:52:30.935112Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
database_1  | 2019-02-07T17:52:30.936066Z 0 [Note] Plugin 'FEDERATED' is disabled.
database_1  | 2019-02-07T17:52:30.940716Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190207 17:52:30
database_1  | 2019-02-07T17:52:30.947277Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
database_1  | 2019-02-07T17:52:30.947747Z 0 [Warning] CA certificate ca.pem is self signed.
database_1  | 2019-02-07T17:52:30.955621Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
database_1  | 2019-02-07T17:52:30.956934Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:30.956966Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:30.956979Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:30.957000Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:30.957006Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:30.957020Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:30.958650Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:30.958670Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:30.965682Z 0 [Note] Event Scheduler: Loaded 0 events
database_1  | 2019-02-07T17:52:30.966086Z 0 [Note] mysqld: ready for connections.
database_1  | Version: '5.7.24'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
database_1  | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
database_1  | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
database_1  | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
database_1  | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
database_1  | 2019-02-07T17:52:33.340222Z 4 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.340242Z 4 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.340249Z 4 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.340265Z 4 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.340270Z 4 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.340278Z 4 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.340301Z 4 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.340308Z 4 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
database_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
database_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
database_1  | mysql: [Warning] Using a password on the command line interface can be insecure.
database_1  | 2019-02-07T17:52:33.361978Z 8 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.362005Z 8 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.362014Z 8 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.362036Z 8 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.362040Z 8 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.362050Z 8 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.362200Z 8 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:33.362210Z 8 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 
database_1  | 2019-02-07T17:52:33.367130Z 0 [Note] Giving 0 client threads a chance to die gracefully
database_1  | 2019-02-07T17:52:33.367186Z 0 [Note] Shutting down slave threads
database_1  | 2019-02-07T17:52:33.367194Z 0 [Note] Forcefully disconnecting 0 remaining clients
database_1  | 2019-02-07T17:52:33.367208Z 0 [Note] Event Scheduler: Purging the queue. 0 events
database_1  | 2019-02-07T17:52:33.367405Z 0 [Note] Binlog end
database_1  | 2019-02-07T17:52:33.369181Z 0 [Note] Shutting down plugin 'ngram'
database_1  | 2019-02-07T17:52:33.369196Z 0 [Note] Shutting down plugin 'partition'
database_1  | 2019-02-07T17:52:33.369200Z 0 [Note] Shutting down plugin 'BLACKHOLE'
database_1  | 2019-02-07T17:52:33.369204Z 0 [Note] Shutting down plugin 'ARCHIVE'
database_1  | 2019-02-07T17:52:33.369207Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
database_1  | 2019-02-07T17:52:33.369237Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
database_1  | 2019-02-07T17:52:33.369243Z 0 [Note] Shutting down plugin 'MyISAM'
database_1  | 2019-02-07T17:52:33.369253Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
database_1  | 2019-02-07T17:52:33.369258Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
database_1  | 2019-02-07T17:52:33.369261Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
database_1  | 2019-02-07T17:52:33.369264Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
database_1  | 2019-02-07T17:52:33.369267Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
database_1  | 2019-02-07T17:52:33.369271Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
database_1  | 2019-02-07T17:52:33.369274Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
database_1  | 2019-02-07T17:52:33.369277Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
database_1  | 2019-02-07T17:52:33.369280Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
database_1  | 2019-02-07T17:52:33.369283Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
database_1  | 2019-02-07T17:52:33.369287Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
database_1  | 2019-02-07T17:52:33.369290Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
database_1  | 2019-02-07T17:52:33.369293Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
database_1  | 2019-02-07T17:52:33.369296Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
database_1  | 2019-02-07T17:52:33.369299Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
database_1  | 2019-02-07T17:52:33.369302Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
database_1  | 2019-02-07T17:52:33.369305Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
database_1  | 2019-02-07T17:52:33.369308Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
database_1  | 2019-02-07T17:52:33.369312Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
database_1  | 2019-02-07T17:52:33.369315Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
database_1  | 2019-02-07T17:52:33.369318Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
database_1  | 2019-02-07T17:52:33.369321Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
database_1  | 2019-02-07T17:52:33.369324Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
database_1  | 2019-02-07T17:52:33.369328Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
database_1  | 2019-02-07T17:52:33.369331Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
database_1  | 2019-02-07T17:52:33.369334Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
database_1  | 2019-02-07T17:52:33.369337Z 0 [Note] Shutting down plugin 'INNODB_CMP'
database_1  | 2019-02-07T17:52:33.369340Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
database_1  | 2019-02-07T17:52:33.369343Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
database_1  | 2019-02-07T17:52:33.369346Z 0 [Note] Shutting down plugin 'INNODB_TRX'
database_1  | 2019-02-07T17:52:33.369349Z 0 [Note] Shutting down plugin 'InnoDB'
database_1  | 2019-02-07T17:52:33.369477Z 0 [Note] InnoDB: FTS optimize thread exiting.
database_1  | 2019-02-07T17:52:33.369581Z 0 [Note] InnoDB: Starting shutdown...
database_1  | 2019-02-07T17:52:33.469890Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
database_1  | 2019-02-07T17:52:33.470534Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 190207 17:52:33
database_1  | 2019-02-07T17:52:34.899401Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12370782
database_1  | 2019-02-07T17:52:34.901455Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
database_1  | 2019-02-07T17:52:34.901470Z 0 [Note] Shutting down plugin 'MEMORY'
database_1  | 2019-02-07T17:52:34.901475Z 0 [Note] Shutting down plugin 'CSV'
database_1  | 2019-02-07T17:52:34.901479Z 0 [Note] Shutting down plugin 'sha256_password'
database_1  | 2019-02-07T17:52:34.901482Z 0 [Note] Shutting down plugin 'mysql_native_password'
database_1  | 2019-02-07T17:52:34.901616Z 0 [Note] Shutting down plugin 'binlog'
database_1  | 2019-02-07T17:52:34.902118Z 0 [Note] mysqld: Shutdown complete
database_1  | 
database_1  | 
database_1  | MySQL init process done. Ready for start up.
database_1  | 
database_1  | 2019-02-07T17:52:35.136544Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
database_1  | 2019-02-07T17:52:35.137626Z 0 [Note] mysqld (mysqld 5.7.24) starting as process 1 ...
database_1  | 2019-02-07T17:52:35.140553Z 0 [Note] InnoDB: PUNCH HOLE support available
database_1  | 2019-02-07T17:52:35.140565Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
database_1  | 2019-02-07T17:52:35.140569Z 0 [Note] InnoDB: Uses event mutexes
database_1  | 2019-02-07T17:52:35.140571Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
database_1  | 2019-02-07T17:52:35.140574Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
database_1  | 2019-02-07T17:52:35.140576Z 0 [Note] InnoDB: Using Linux native AIO
database_1  | 2019-02-07T17:52:35.140851Z 0 [Note] InnoDB: Number of pools: 1
database_1  | 2019-02-07T17:52:35.140973Z 0 [Note] InnoDB: Using CPU crc32 instructions
database_1  | 2019-02-07T17:52:35.142199Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
database_1  | 2019-02-07T17:52:35.149701Z 0 [Note] InnoDB: Completed initialization of buffer pool
database_1  | 2019-02-07T17:52:35.151346Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
database_1  | 2019-02-07T17:52:35.162801Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
database_1  | 2019-02-07T17:52:35.186987Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
database_1  | 2019-02-07T17:52:35.187118Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
database_1  | 2019-02-07T17:52:35.214982Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
database_1  | 2019-02-07T17:52:35.216253Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
database_1  | 2019-02-07T17:52:35.216274Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
database_1  | 2019-02-07T17:52:35.217388Z 0 [Note] InnoDB: 5.7.24 started; log sequence number 12370782
database_1  | 2019-02-07T17:52:35.217995Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
database_1  | 2019-02-07T17:52:35.218431Z 0 [Note] Plugin 'FEDERATED' is disabled.
database_1  | 2019-02-07T17:52:35.222687Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190207 17:52:35
database_1  | 2019-02-07T17:52:35.225225Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
database_1  | 2019-02-07T17:52:35.225480Z 0 [Warning] CA certificate ca.pem is self signed.
database_1  | 2019-02-07T17:52:35.227622Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
database_1  | 2019-02-07T17:52:35.227665Z 0 [Note] IPv6 is available.
database_1  | 2019-02-07T17:52:35.227987Z 0 [Note]   - '::' resolves to '::';
database_1  | 2019-02-07T17:52:35.228011Z 0 [Note] Server socket created on IP: '::'.
database_1  | 2019-02-07T17:52:35.231849Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
database_1  | 2019-02-07T17:52:35.234816Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:35.234901Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:35.234947Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:35.235061Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:35.235082Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:35.235127Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:35.241898Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:35.241971Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
database_1  | 2019-02-07T17:52:35.258927Z 0 [Note] Event Scheduler: Loaded 0 events
database_1  | 2019-02-07T17:52:35.259394Z 0 [Note] mysqld: ready for connections.
database_1  | Version: '5.7.24'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
api_1       | nginx: running bootstrap...
database_1  | 2019-02-07T17:52:35.881856Z 2 [Note] Got an error reading communication packets
api_1       | Connecting to the database...
api_1       | Installing database...
api_1       | Installing data...
api_1       | 
api_1       |  Directus database installed.
api_1       | 
api_1       | nginx: starting...
api_1       | 2019/02/07 17:52:37 [notice] 191#191: using the "epoll" event method
api_1       | 2019/02/07 17:52:37 [notice] 191#191: nginx/1.14.2
api_1       | 2019/02/07 17:52:37 [notice] 191#191: OS: Linux 4.14.94-1-MANJARO
api_1       | 2019/02/07 17:52:37 [notice] 191#191: getrlimit(RLIMIT_NOFILE): 1048576:1048576
api_1       | 2019/02/07 17:52:37 [notice] 191#191: start worker processes
api_1       | 2019/02/07 17:52:37 [notice] 191#191: start worker process 234
</pre>
</details>

**Comment by samvasko** [comment] 2019-02-09 19:22
I had the same issue and resolved it by using the latest tagged version.
You can disable CORS in your browser.

**Comment by PostPollux** [comment] 2019-02-10 13:46
Thanks, I can confirm this. It only happens with the "latest" tag which is 3 days old.
If I use "directus/api:2.0.16" and "directus/app:7.0.16" which are 13 days old, the CORS error is gone.

**Comment by Steven-Harris** [comment] 2019-02-11 19:16
I am having a similar issue.  Everything worked at first but when I restarted my containers I got some weird errors. downgrading didn't work
>Access to XMLHttpRequest at 'https://apidomain/server/ping' from origin 'https://manage.metoospringfield.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, https://appdomain', but only one is allowed

**Comment by samvasko** [comment] 2019-02-20 22:38
The bug is likely not CORS related at all. Its the server error that causes an empty response being returned. Without the CORS headers the client cannot read it.

**Comment by mvhirsch** [comment] 2019-04-26 13:29
I cannot reproduce this issue with API 2.0.18 and APP 7.0.18. 
Can you confirm this, please?

To avoid such riddles with docker, I would advise to pin your version and not using `:latest` since this might be cached (like other tags in docker, too). Maybe there was an issue with the building process and `:latest` was broken? Reading some comments on recent issues confirms a problem in building docker images by now.

**Comment by am-webdev** [comment] 2019-05-03 10:13
Hi I'm running the :latest container and I'm affected by the CORS issues as well. 

My setup is the following: 

- reverse proxy
   - directus mysql container
   - api: hostname: api.example.com
      - links the db container as mysql host
   - app: hostname: directus.example.com
      - API_ENDPOINT: "API; https://api.example.com/_/"

Results in CORS browser error while accessing the login screen

`Access to XMLHttpRequest at 'https://api.example.com/server/ping' from origin 'https://directus.example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

So here's the full compose file

```
version: "3"
services:
  # Directus Database
  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ""
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
  # API
  api:
    image: directus/api:latest
    environment:
      DATABASE_HOST: database
      DATABASE_NAME: ""
      DATABASE_USERNAME: ""
      DATABASE_PASSWORD: ""
      ADMIN_EMAIL: ""
      ADMIN_PASSWORD: ""
      VIRTUAL_HOST: "api.example.com"
      LETSENCRYPT_HOST: "api.example.com"
      LETSENCRYPT_EMAIL: ""
    ports:
      - 7000
  # Dashboard
  app:
    image: directus/app:latest
    environment:
      API_ENDPOINT: "API; https://api.example.com/_/"
      VIRTUAL_HOST: "directus.example.com"
      LETSENCRYPT_HOST: "directus.example.com"
      LETSENCRYPT_EMAIL: ""
      ALLOW_OTHER_API: "true"
    ports:
      - 80
networks:
  default:
    external:
      name: webproxy
```

Is it possible to change the value for CORS via Docker env?

**Comment by mvhirsch** [comment] 2019-05-04 09:25
@am-webdev seems like your reverse-proxy is causing the issue. Using your docker-compose file, I'm not able to reproduce this issue. Can you please check your reverse-proxy configuration and/or retry without such?

**Comment by mvhirsch** [comment] 2019-05-04 09:26
> Is it possible to change the value for CORS via Docker env?

Yes, just set the following option in your api environment: 

    CORS_MAX_AGE: 500

**Comment by am-webdev** [comment] 2019-05-06 05:48
Hi @mvhirsch  this seams to work perfectly. Unfortunately I'm now running into this issue: https://github.com/directus/docker/issues/19

**Comment by mvhirsch** [comment] 2019-05-07 07:51
Seems like, there is no bug. @benhaynes can you please close this?

**Comment by benhaynes** [comment] 2019-05-07 11:43
Indeed!

**Closed by benhaynes** 2019-05-07 11:43 UTC
Labels: before-refactor, bug
