### ISSUE TITLE
Change API url on the Dashboard (APP)

### ISSUE THREAD

**Issue by pdsm** [directus/docker#23] opened 2019-02-09 12:35 UTC
I am trying to use **Directus 7** in docker and I have encountered the following problem:

I have not been able to change the API URL in the Dashboard (APP), no matter what I assign to the environment variable **API_ENDPOINT** or **API_URL**. Whenever I open the dashboard it tries to go to the url **http: // localhost: 7000..../ping**, and since the API is not found there, it fails.

Is there any way to change the API URL in the dashboard in Docker? I am using the images: directus/api:latest and directus/app:latest

Thank you

**Comment by PostPollux** [comment] 2019-02-10 23:08
I think I'm stuck at exactly the same point. Everything works in the basic setup (localhost setup) as long as I don't change anything in the docker-compse example. But I want to use Directus 7 behind the jwilder nginx reverse proxy. No matter what I set API_ENDPOINT to, the app does not seem to care.

Here for example i set it to "API; http://localhost:5000/_/" but it still looks for port 7000:


And in this second screenshot example I have it running behind the reverse proxy. That's why the address of the app is "directus.localhost" which seems to work, at least the login screen appears. The api contianer also runs behind this reverse proxy and is reachable with "directusapi.localhost" over port 80. If I enter "directusapi.localhost" in the browser I get this response: "{"error":{"code":108,"message":"User not authenticated"}}" So the container is clearly reachable with this address. So I set the API_ENDPOINT to "API; http://directusapi.localhost/_/". But this is the error I get:

**Comment by WoLfulus** [comment] 2019-02-11 12:20
I'll take a look at this.

**Comment by samvasko** [comment] 2019-02-11 17:32
Could you disable you cache and retry?

**Comment by pdsm** [comment] 2019-02-11 22:43
> Could you disable you cache and retry? Mine is always loaded from cache.

This fixed the problem, thanks!!

**Comment by samvasko** [comment] 2019-02-12 10:00
Other possible solutions:
 - Configure caching
 - Programatically add version to the config file
 - Do nothing / Add comments to the JS file to warn the editors.

Ref:
https://medium.com/pixelpoint/best-practices-for-cache-control-settings-for-your-website-ff262b38c5a2

**Comment by PostPollux** [comment] 2019-02-12 14:38
I can confirm it fixes the problem! Thanks @samvasko !!!
Now directus seems to flawlessly run behind my reverse-proxy with ssl!

But I still think this should be fixed in some way or at least be documented somewhere...

**Comment by benhaynes** [comment] 2019-02-12 16:51
@WoLfulus @samvasko @WellingGuzman 

What could we add to the Docs to make this clearer? Is this specifically an API or Docker issue? Also, it's probably about time to add a dedicated "docker" section to [the Docs](https://github.com/directus/docs)... probably as a "Guide" or under "Advanced".

Do any of you have thoughts on this?

**Comment by mvhirsch** [comment] 2019-04-26 13:17
I cannot reproduce this with API v2.0.18 and APP v7.0.18.

My browser is always reloading (`Cache-Control: public, must-revalidate, proxy-revalidate` and `If-Not-Modified`/`If-None-Match` headers) the _/config.js_.

There shouldn't be an issue any more. Can anyone still reproduce this?

**Comment by WoLfulus** [comment] 2019-12-17 04:08
I'm closing this one since we have changed how app/api works (now they are bundled together) and this doesn't apply anymore.

**Closed by WoLfulus** 2019-12-17 04:08 UTC
Labels: before-refactor, bug, question
